Downgrade to 2018 edition
```
> cargo hack check --all --rust-version --no-private
error: process didn't exit successfully: `rustup run 1.31 cargo generate-lockfile --manifest-path Cargo.toml` (exit status: 101)
--- stderr
    Updating crates.io index
    Updating git repository `https://github.com/taiki-e/trybuild`
error: no matching package named `trybuild` found
location searched: https://github.com/taiki-e/trybuild?branch=dev
required by package `easy-ext v1.0.1 (/Users/taiki/projects/sources/taiki-e/easy-ext)`
```